name: Build and Release

on:
  push:
    tags:
      - "v*"  # Trigger only when a tag starting with "v" is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python and PyInstaller
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip zip
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build the executable
        run: |
          pyinstaller --onefile --name rapl-energy-meter main.py
          mv dist/rapl-energy-meter .  # Move binary to root directory

      - name: Create a ZIP archive of the source code
        run: |
          zip -r source_code.zip . -x "source_code.zip" "dist/*" "build/*" "*.spec" ".git/*" ".github/*"

      - name: Verify generated files
        run: |
          ls -lh
          [ -f rapl-energy-meter ] && echo "Executable exists" || echo "ERROR: Executable missing!"
          [ -f source_code.zip ] && echo "Source code ZIP exists" || echo "ERROR: Source ZIP missing!"

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            rapl-energy-meter
            source_code.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the new PAT token
